apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dualvalidateservice-data
  namespace: mbms-morder-feature
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
